/**
 * Brand normalization dictionary v2.0
 * Maps common variations to canonical brand names
 * 
 * Total entries: 320+
 * Categories: Supermarkets, Fast Food, Restaurants, Tech, Streaming,
 *             Clothing, Fuel, Transport, Utilities, Banks, Home & Garden,
 *             Sports, Beauty, Pharmacies, Electronics, Coffee, Hotels, Airlines
 */
export const BRAND_DICT: Record<string, string> = {
    // =====================================================
    // SUPERMARKETS & GROCERY (50+)
    // =====================================================
    "ESSELUNGA": "ESSELUNGA",
    "ESSE LUNGA": "ESSELUNGA",
    "ESSELUNGA VIA": "ESSELUNGA",
    "ESSELUNGA VIALE": "ESSELUNGA",
    "COOP": "COOP",
    "COOP ITALIA": "COOP",
    "COOP LOMBARDIA": "COOP",
    "COOP ALLEANZA": "COOP",
    "IPERCOOP": "COOP",
    "CONAD": "CONAD",
    "CONAD CITY": "CONAD",
    "CONAD SUPERSTORE": "CONAD",
    "CONAD ADRIATICO": "CONAD",
    "CARREFOUR": "CARREFOUR",
    "CARREFOUR EXPRESS": "CARREFOUR",
    "CARREFOUR MARKET": "CARREFOUR",
    "CARREFOUR IPER": "CARREFOUR",
    "EUROSPIN": "EUROSPIN",
    "EUROSPIN ITALIA": "EUROSPIN",
    "LIDL": "LIDL",
    "LIDL ITALIA": "LIDL",
    "ALDI": "ALDI",
    "ALDI ITALIA": "ALDI",
    "MD DISCOUNT": "MD",
    "MD SPA": "MD",
    "PENNY MARKET": "PENNY MARKET",
    "PENNY": "PENNY MARKET",
    "PAM": "PAM",
    "PAM PANORAMA": "PAM",
    "PANORAMA": "PAM",
    "IPER": "IPER",
    "IPER LA GRANDE": "IPER",
    "BENNET": "BENNET",
    "BENNET SPA": "BENNET",
    "FAMILA": "FAMILA",
    "A&O": "A&O",
    "TIGROS": "TIGROS",
    "IL GIGANTE": "IL GIGANTE",
    "SIMPLY": "AUCHAN",
    "AUCHAN": "AUCHAN",
    "DESPAR": "DESPAR",
    "INTERSPAR": "DESPAR",
    "EUROSPAR": "DESPAR",
    "SIGMA": "SIGMA",
    "U2 SUPERMERCATO": "U2",
    "NATURASI": "NATURASI",
    "NATURA SI": "NATURASI",
    "TODIS": "TODIS",
    "TUODI": "TUODI",
    "INS": "INS",
    "PEWEX": "PEWEX",
    "POLI": "POLI",
    "ALI SUPERMERCATI": "ALI",
    "ALIPER": "ALIPER",
    "CADORO": "CADORO",
    "PRIX": "PRIX",
    "DPIÙ": "DPIU",
    "DPIU": "DPIU",

    // =====================================================
    // FAST FOOD & QUICK SERVICE (30+)
    // =====================================================
    "MCDONALD": "MCDONALD",
    "MC DONALD": "MCDONALD",
    "MC DONALDS": "MCDONALD",
    "MCDONALDS": "MCDONALD",
    "BURGER KING": "BURGER KING",
    "BURGERKING": "BURGER KING",
    "OLD WILD": "OLD WILD WEST",
    "OLD WILD WEST": "OLD WILD WEST",
    "OLDWILDWEST": "OLD WILD WEST",
    "KFC": "KFC",
    "KENTUCKY FRIED": "KFC",
    "SUBWAY": "SUBWAY",
    "DOMINOS": "DOMINOS",
    "DOMINO S": "DOMINOS",
    "PIZZA HUT": "PIZZA HUT",
    "PIZZAHUT": "PIZZA HUT",
    "FIVE GUYS": "FIVE GUYS",
    "FIVEGUYS": "FIVE GUYS",
    "CHIPOTLE": "CHIPOTLE",
    "POKE HOUSE": "POKE HOUSE",
    "POKEHOUSE": "POKE HOUSE",
    "WAGAMAMA": "WAGAMAMA",
    "ROADHOUSE": "ROADHOUSE",
    "ROAD HOUSE": "ROADHOUSE",
    "ALICE PIZZA": "ALICE PIZZA",
    "LA PIADINERIA": "LA PIADINERIA",
    "PIADINERIA": "LA PIADINERIA",
    "SPONTINI": "SPONTINI",
    "ROSSOPOMODORO": "ROSSOPOMODORO",
    "ROSSO POMODORO": "ROSSOPOMODORO",
    "CHEF EXPRESS": "CHEF EXPRESS",
    "AUTOGRILL": "AUTOGRILL",
    "MYCHEF": "MYCHEF",
    "EATALY": "EATALY",

    // =====================================================
    // COFFEE & BAKERY (20+)
    // =====================================================
    "STARBUCKS": "STARBUCKS",
    "STARBUCKS COFFEE": "STARBUCKS",
    "COSTA COFFEE": "COSTA COFFEE",
    "COSTACOFFEE": "COSTA COFFEE",
    "MCCAFE": "MCCAFE",
    "MC CAFE": "MCCAFE",
    "LAVAZZA": "LAVAZZA",
    "ILLY": "ILLY",
    "ILLYCAFFE": "ILLY",
    "NESPRESSO": "NESPRESSO",
    "GROM": "GROM",
    "VENCHI": "VENCHI",
    "CIOCCOLATITALIANI": "CIOCCOLATITALIANI",
    "AMORINO": "AMORINO",
    "PANINO GIUSTO": "PANINO GIUSTO",
    "PANS AND COMPANY": "PANS AND COMPANY",
    "PRET A MANGER": "PRET A MANGER",
    "CRACCO": "CRACCO",
    "PRINCI": "PRINCI",
    "PASTICCERIA": "PASTICCERIA",

    // =====================================================
    // STREAMING & ENTERTAINMENT (25+)
    // =====================================================
    "NETFLIX": "NETFLIX",
    "NETFLIX COM": "NETFLIX",
    "NETFLIX.COM": "NETFLIX",
    "SPOTIFY": "SPOTIFY",
    "SPOTIFY AB": "SPOTIFY",
    "SPOTIFY PREMIUM": "SPOTIFY",
    "APPLE": "APPLE",
    "APPLE COM": "APPLE",
    "APPLE.COM": "APPLE",
    "ITUNES": "APPLE",
    "APPLE MUSIC": "APPLE",
    "DISNEY PLUS": "DISNEY PLUS",
    "DISNEYPLUS": "DISNEY PLUS",
    "DISNEY+": "DISNEY PLUS",
    "AMAZON PRIME": "AMAZON PRIME",
    "PRIME VIDEO": "AMAZON PRIME",
    "PRIMEVIDEO": "AMAZON PRIME",
    "HBO MAX": "HBO MAX",
    "HBOMAX": "HBO MAX",
    "PARAMOUNT": "PARAMOUNT",
    "PARAMOUNT PLUS": "PARAMOUNT",
    "DAZN": "DAZN",
    "SKY": "SKY",
    "SKY ITALIA": "SKY",
    "NOW TV": "NOW TV",
    "NOWTV": "NOW TV",
    "TIM VISION": "TIMVISION",
    "TIMVISION": "TIMVISION",
    "YOUTUBE": "YOUTUBE",
    "YOUTUBE PREMIUM": "YOUTUBE",
    "TWITCH": "TWITCH",
    "PLAYSTATION": "PLAYSTATION",
    "PSN": "PLAYSTATION",
    "XBOX": "XBOX",
    "XBOX LIVE": "XBOX",
    "STEAM": "STEAM",
    "EPIC GAMES": "EPIC GAMES",
    "NINTENDO": "NINTENDO",
    "AUDIBLE": "AUDIBLE",
    "KINDLE": "KINDLE",

    // =====================================================
    // TECH & E-COMMERCE (40+)
    // =====================================================
    "AMAZON": "AMAZON",
    "AMZN": "AMAZON",
    "AMAZON EU": "AMAZON",
    "AMAZON IT": "AMAZON",
    "AMZN MKTP": "AMAZON",
    "AMAZON MARKETPLACE": "AMAZON",
    "GOOGLE": "GOOGLE",
    "GOOGLE PAY": "GOOGLE",
    "GOOGLE PLAY": "GOOGLE",
    "GOOGLE CLOUD": "GOOGLE",
    "FACEBOOK": "META",
    "FB ADS": "META",
    "META": "META",
    "INSTAGRAM": "META",
    "WHATSAPP": "META",
    "MICROSOFT": "MICROSOFT",
    "MICROSOFT 365": "MICROSOFT",
    "OFFICE 365": "MICROSOFT",
    "LINKEDIN": "LINKEDIN",
    "ADOBE": "ADOBE",
    "ADOBE CREATIVE": "ADOBE",
    "DROPBOX": "DROPBOX",
    "ICLOUD": "APPLE",
    "ZOOM": "ZOOM",
    "SLACK": "SLACK",
    "NOTION": "NOTION",
    "CANVA": "CANVA",
    "EBAY": "EBAY",
    "ALIEXPRESS": "ALIEXPRESS",
    "ALI EXPRESS": "ALIEXPRESS",
    "WISH": "WISH",
    "SHEIN": "SHEIN",
    "TEMU": "TEMU",
    "ZALANDO": "ZALANDO",
    "ASOS": "ASOS",
    "YOOX": "YOOX",
    "VINTED": "VINTED",
    "SUBITO": "SUBITO",
    "SUBITO IT": "SUBITO",
    "WALLAPOP": "WALLAPOP",
    "PAYPAL": "PAYPAL",
    "PAYPAL EUROPE": "PAYPAL",
    "STRIPE": "STRIPE",
    "KLARNA": "KLARNA",
    "SATISPAY": "SATISPAY",
    "REVOLUT": "REVOLUT",
    "WISE": "WISE",
    "TRANSFERWISE": "WISE",
    "SUMUP": "SUMUP",
    "SQUARE": "SQUARE",

    // =====================================================
    // CLOTHING & FASHION (50+)
    // =====================================================
    "ZARA": "ZARA",
    "ZARA ROMA": "ZARA",
    "ZARA MILANO": "ZARA",
    "H&M": "H&M",
    "H M": "H&M",
    "HM": "H&M",
    "HENNES MAURITZ": "H&M",
    "UNIQLO": "UNIQLO",
    "PRIMARK": "PRIMARK",
    "PULL AND BEAR": "PULL & BEAR",
    "PULL&BEAR": "PULL & BEAR",
    "BERSHKA": "BERSHKA",
    "STRADIVARIUS": "STRADIVARIUS",
    "MASSIMO DUTTI": "MASSIMO DUTTI",
    "OYSHO": "OYSHO",
    "MANGO": "MANGO",
    "INTIMISSIMI": "INTIMISSIMI",
    "CALZEDONIA": "CALZEDONIA",
    "TEZENIS": "TEZENIS",
    "YAMAMAY": "YAMAMAY",
    "OVIESSE": "OVS",
    "OVS": "OVS",
    "UPIM": "UPIM",
    "COIN": "COIN",
    "LA RINASCENTE": "RINASCENTE",
    "RINASCENTE": "RINASCENTE",
    "BENETTON": "BENETTON",
    "SISLEY": "SISLEY",
    "DIESEL": "DIESEL",
    "GUESS": "GUESS",
    "TOMMY HILFIGER": "TOMMY HILFIGER",
    "TOMMY": "TOMMY HILFIGER",
    "RALPH LAUREN": "RALPH LAUREN",
    "POLO RALPH": "RALPH LAUREN",
    "LACOSTE": "LACOSTE",
    "CALVIN KLEIN": "CALVIN KLEIN",
    "CK": "CALVIN KLEIN",
    "LEVI S": "LEVIS",
    "LEVIS": "LEVIS",
    "GAP": "GAP",
    "BANANA REPUBLIC": "BANANA REPUBLIC",
    "NIKE": "NIKE",
    "ADIDAS": "ADIDAS",
    "PUMA": "PUMA",
    "REEBOK": "REEBOK",
    "NEW BALANCE": "NEW BALANCE",
    "CONVERSE": "CONVERSE",
    "VANS": "VANS",
    "FOOTLOCKER": "FOOT LOCKER",
    "FOOT LOCKER": "FOOT LOCKER",
    "SNIPES": "SNIPES",
    "JD SPORTS": "JD SPORTS",
    "CISALFA": "CISALFA",
    "MAXI SPORT": "MAXI SPORT",
    "PITTARELLO": "PITTARELLO",
    "BATA": "BATA",
    "GEOX": "GEOX",
    "SCARPE E SCARPE": "SCARPE E SCARPE",

    // =====================================================
    // HOME & GARDEN (25+)
    // =====================================================
    "IKEA": "IKEA",
    "IKEA ITALIA": "IKEA",
    "LEROY MERLIN": "LEROY MERLIN",
    "LEROYMERLIN": "LEROY MERLIN",
    "BRICO": "BRICO",
    "BRICOMAN": "BRICOMAN",
    "BRICOCENTER": "BRICOCENTER",
    "OBI": "OBI",
    "CASTORAMA": "CASTORAMA",
    "MAISON DU MONDE": "MAISON DU MONDE",
    "MAISONS DU MONDE": "MAISON DU MONDE",
    "MONDO CONVENIENZA": "MONDO CONVENIENZA",
    "MONDOCONV": "MONDO CONVENIENZA",
    "POLTRONE SOFA": "POLTRONESOFÀ",
    "POLTRONESOFÀ": "POLTRONESOFÀ",
    "MERCATONE": "MERCATONE UNO",
    "DIVANI DIVANI": "DIVANI & DIVANI",
    "KASANOVA": "KASANOVA",
    "CASA": "CASA",
    "CASA SHOP": "CASA",
    "TIGER": "FLYING TIGER",
    "FLYING TIGER": "FLYING TIGER",
    "ZARA HOME": "ZARA HOME",
    "H&M HOME": "H&M HOME",
    "THUN": "THUN",
    "COINCASA": "COINCASA",
    "CONFORAMA": "CONFORAMA",

    // =====================================================
    // ELECTRONICS (30+)
    // =====================================================
    "MEDIAWORLD": "MEDIAWORLD",
    "MEDIA WORLD": "MEDIAWORLD",
    "UNIEURO": "UNIEURO",
    "EURONICS": "EURONICS",
    "TRONY": "TRONY",
    "EXPERT": "EXPERT",
    "APPLE STORE": "APPLE STORE",
    "SAMSUNG": "SAMSUNG",
    "HUAWEI": "HUAWEI",
    "XIAOMI": "XIAOMI",
    "GAMESPOT": "GAMESTOP",
    "GAMESTOP": "GAMESTOP",
    "GAME STOP": "GAMESTOP",
    "MONDADORI": "MONDADORI",
    "FELTRINELLI": "FELTRINELLI",
    "LA FELTRINELLI": "FELTRINELLI",
    "FNAC": "FNAC",

    // =====================================================
    // FUEL & AUTOMOTIVE (25+)
    // =====================================================
    "ENI": "ENI",
    "AGIP": "ENI",
    "ENISTATION": "ENI",
    "Q8": "Q8",
    "KUWAIT": "Q8",
    "IP": "IP",
    "ITALIANA PETROLI": "IP",
    "TAMOIL": "TAMOIL",
    "SHELL": "SHELL",
    "ESSO": "ESSO",
    "TOTAL": "TOTAL",
    "TOTALENERGIES": "TOTAL",
    "BP": "BP",
    "BRITISH PETROLEUM": "BP",
    "REPSOL": "REPSOL",
    "API": "API",
    "ERG": "ERG",
    "KEROPETROL": "KEROPETROL",
    "COSTANTIN": "COSTANTIN",
    "NORAUTO": "NORAUTO",
    "MIDAS": "MIDAS",
    "CARGLASS": "CARGLASS",
    "EUROMASTER": "EUROMASTER",
    "DRIVER CENTER": "DRIVER CENTER",
    "MICHELIN": "MICHELIN",

    // =====================================================
    // TRANSPORT & MOBILITY (30+)
    // =====================================================
    "AUTOSTRADE": "AUTOSTRADE",
    "AUTOSTRADE PER": "AUTOSTRADE",
    "TELEPASS": "TELEPASS",
    "TELEPASS PAY": "TELEPASS",
    "TRENITALIA": "TRENITALIA",
    "ITALO": "ITALO",
    "ITALOTRENO": "ITALO",
    "NTV": "ITALO",
    "TRENORD": "TRENORD",
    "ATM": "ATM MILANO",
    "ATM MILANO": "ATM MILANO",
    "ATAC": "ATAC",
    "GTT": "GTT",
    "ANM": "ANM",
    "COTRAL": "COTRAL",
    "UBER": "UBER",
    "UBER BV": "UBER",
    "UBER ITALY": "UBER",
    "LYFT": "LYFT",
    "BOLT": "BOLT",
    "FREENOW": "FREENOW",
    "FREE NOW": "FREENOW",
    "MYTAXI": "FREENOW",
    "BLABLACAR": "BLABLACAR",
    "FLIXBUS": "FLIXBUS",
    "MARINO BUS": "MARINOBUS",
    "MARINOBUS": "MARINOBUS",
    "ENJOY": "ENJOY",
    "SHARENOW": "SHARE NOW",
    "SHARE NOW": "SHARE NOW",
    "CAR2GO": "SHARE NOW",
    "LEASYS": "LEASYS",
    "ARVAL": "ARVAL",
    "ALD": "ALD",
    "HERTZ": "HERTZ",
    "AVIS": "AVIS",
    "EUROPCAR": "EUROPCAR",
    "SIXT": "SIXT",
    "BUDGET": "BUDGET",
    "LOCAUTO": "LOCAUTO",
    "MAGGIORE": "MAGGIORE",

    // =====================================================
    // AIRLINES & TRAVEL (30+)
    // =====================================================
    "ALITALIA": "ITA AIRWAYS",
    "ITA AIRWAYS": "ITA AIRWAYS",
    "RYANAIR": "RYANAIR",
    "EASYJET": "EASYJET",
    "EASY JET": "EASYJET",
    "VUELING": "VUELING",
    "WIZZAIR": "WIZZ AIR",
    "WIZZ AIR": "WIZZ AIR",
    "LUFTHANSA": "LUFTHANSA",
    "BRITISH AIRWAYS": "BRITISH AIRWAYS",
    "AIR FRANCE": "AIR FRANCE",
    "KLM": "KLM",
    "EMIRATES": "EMIRATES",
    "QATAR AIRWAYS": "QATAR AIRWAYS",
    "TURKISH AIRLINES": "TURKISH AIRLINES",
    "IBERIA": "IBERIA",
    "TAP": "TAP",
    "SWISS": "SWISS",
    "AUSTRIAN": "AUSTRIAN",
    "BOOKING": "BOOKING",
    "BOOKING COM": "BOOKING",
    "BOOKING.COM": "BOOKING",
    "EXPEDIA": "EXPEDIA",
    "HOTELS COM": "HOTELS.COM",
    "AIRBNB": "AIRBNB",
    "VRBO": "VRBO",
    "TRIPADVISOR": "TRIPADVISOR",
    "SKYSCANNER": "SKYSCANNER",
    "KAYAK": "KAYAK",
    "TRIVAGO": "TRIVAGO",
    "LASTMINUTE": "LASTMINUTE",
    "EDREAMS": "EDREAMS",
    "VOLAGRATIS": "VOLAGRATIS",

    // =====================================================
    // HOTELS & HOSPITALITY (20+)
    // =====================================================
    "HILTON": "HILTON",
    "MARRIOTT": "MARRIOTT",
    "SHERATON": "SHERATON",
    "HOLIDAY INN": "HOLIDAY INN",
    "IHG": "IHG",
    "ACCOR": "ACCOR",
    "IBIS": "IBIS",
    "NOVOTEL": "NOVOTEL",
    "MERCURE": "MERCURE",
    "BEST WESTERN": "BEST WESTERN",
    "NH HOTELS": "NH HOTELS",
    "RADISSON": "RADISSON",
    "CROWNE PLAZA": "CROWNE PLAZA",
    "HYATT": "HYATT",
    "FOUR SEASONS": "FOUR SEASONS",
    "RITZ CARLTON": "RITZ CARLTON",
    "W HOTEL": "W HOTEL",
    "HOSTELWORLD": "HOSTELWORLD",
    "BELVILLA": "BELVILLA",

    // =====================================================
    // UTILITIES & TELECOM (25+)
    // =====================================================
    "ENEL": "ENEL",
    "ENEL ENERGIA": "ENEL",
    "A2A": "A2A",
    "EDISON": "EDISON",
    "ENI GAS": "ENI",
    "ENI LUCE": "ENI",
    "PLENITUDE": "ENI",
    "SORGENIA": "SORGENIA",
    "ENGIE": "ENGIE",
    "HERA": "HERA",
    "IREN": "IREN",
    "ACEA": "ACEA",
    "TIM": "TIM",
    "TELECOM ITALIA": "TIM",
    "VODAFONE": "VODAFONE",
    "WIND": "WINDTRE",
    "TRE": "WINDTRE",
    "WINDTRE": "WINDTRE",
    "WIND TRE": "WINDTRE",
    "ILIAD": "ILIAD",
    "FASTWEB": "FASTWEB",
    "POSTE MOBILE": "POSTEMOBILE",
    "POSTEMOBILE": "POSTEMOBILE",
    "HO MOBILE": "HO MOBILE",
    "KENA MOBILE": "KENA MOBILE",
    "VERY MOBILE": "VERY MOBILE",
    "COOP VOCE": "COOPVOCE",
    "COOPVOCE": "COOPVOCE",
    "TISCALI": "TISCALI",

    // =====================================================
    // BANKS & FINANCIAL (20+)
    // =====================================================
    "INTESA SANPAOLO": "INTESA SANPAOLO",
    "INTESA": "INTESA SANPAOLO",
    "UNICREDIT": "UNICREDIT",
    "BANCA INTESA": "INTESA SANPAOLO",
    "BNL": "BNL",
    "BPER": "BPER",
    "BANCO BPM": "BANCO BPM",
    "MPS": "MPS",
    "MONTE PASCHI": "MPS",
    "CREDEM": "CREDEM",
    "FINECO": "FINECO",
    "WIDIBA": "WIDIBA",
    "N26": "N26",
    "HYPE": "HYPE",
    "BUDDYBANK": "BUDDYBANK",
    "ING": "ING",
    "ING DIRECT": "ING",
    "POSTE ITALIANE": "POSTE ITALIANE",
    "BANCOPOSTA": "POSTE ITALIANE",
    "MEDIOLANUM": "MEDIOLANUM",
    "DEUTSCHE BANK": "DEUTSCHE BANK",
    "CREDIT AGRICOLE": "CREDIT AGRICOLE",
    "FINDOMESTIC": "FINDOMESTIC",
    "FINDOMESTIC BANCA": "FINDOMESTIC",
    "AGOS": "AGOS",
    "AGOS DUCATO": "AGOS",
    "COFIDIS": "COFIDIS",

    // =====================================================
    // HEALTH & PHARMACY (15+)
    // =====================================================
    "FARMACIE": "FARMACIA",
    "FARMACIA": "FARMACIA",
    "LLOYDS FARMACIA": "LLOYDS FARMACIA",
    "DR MAX": "DR MAX",
    "APOTECA NATURA": "APOTECA NATURA",
    "BOOTS": "BOOTS",
    "PARAFARMACIA": "PARAFARMACIA",
    "SANITARIA": "SANITARIA",
    "OTTICA": "OTTICA",
    "FIELMANN": "FIELMANN",
    "SALMOIRAGHI": "SALMOIRAGHI",
    "GRANDVISION": "GRANDVISION",
    "VISION": "VISION",
    "AFFIDEA": "AFFIDEA",
    "SYNLAB": "SYNLAB",

    // =====================================================
    // BEAUTY & PERSONAL CARE (20+)
    // =====================================================
    "SEPHORA": "SEPHORA",
    "DOUGLAS": "DOUGLAS",
    "KIKO": "KIKO",
    "WYCON": "WYCON",
    "MAC": "MAC COSMETICS",
    "MAC COSMETICS": "MAC COSMETICS",
    "LUSH": "LUSH",
    "BODY SHOP": "THE BODY SHOP",
    "THE BODY SHOP": "THE BODY SHOP",
    "YVES ROCHER": "YVES ROCHER",
    "BOTTEGA VERDE": "BOTTEGA VERDE",
    "ACQUA E SAPONE": "ACQUA E SAPONE",
    "TIGOTA": "TIGOTÀ",
    "TIGOTÀ": "TIGOTÀ",
    "IPERSOAP": "IPERSOAP",
    "CADDY S": "CADDYS",
    "CADDYS": "CADDYS",
    "RITUALS": "RITUALS",
    "LOCCITANE": "LOCCITANE",
    "NYX": "NYX",

    // =====================================================
    // SPORTS & FITNESS (15+)
    // =====================================================
    "DECATHLON": "DECATHLON",
    "CISALFA SPORT": "CISALFA",
    "DF SPORT": "DF SPORT",
    "SPORTLER": "SPORTLER",
    "VIRGIN ACTIVE": "VIRGIN ACTIVE",
    "MCFIT": "MCFIT",
    "FITNESS FIRST": "FITNESS FIRST",
    "ANYTIME FITNESS": "ANYTIME FITNESS",
    "TECHNOGYM": "TECHNOGYM",
    "PALESTRA": "PALESTRA",
    "GYM": "GYM",
    "CROSSFIT": "CROSSFIT",
    "YOGA": "YOGA",
    "PILATES": "PILATES",
    "PISCINA": "PISCINA",

    // =====================================================
    // FOOD DELIVERY (10+)
    // =====================================================
    "DELIVEROO": "DELIVEROO",
    "GLOVO": "GLOVO",
    "JUST EAT": "JUST EAT",
    "JUSTEAT": "JUST EAT",
    "UBER EATS": "UBER EATS",
    "UBEREATS": "UBER EATS",
    "FOODORA": "FOODORA",
    "GETIR": "GETIR",
    "GORILLAS": "GORILLAS",
    "FLINK": "FLINK",
    "EVERLI": "EVERLI",
    "SUPERMERCATO24": "EVERLI",

    // =====================================================
    // INSURANCE (10+)
    // =====================================================
    "GENERALI": "GENERALI",
    "ALLIANZ": "ALLIANZ",
    "AXA": "AXA",
    "UNIPOL": "UNIPOL",
    "UNIPOLSAI": "UNIPOL",
    "ZURICH": "ZURICH",
    "REALE MUTUA": "REALE MUTUA",
    "PRIMA ASSICURAZIONI": "PRIMA",
    "PRIMA": "PRIMA",
    "VERTI": "VERTI",
    "QUIXA": "QUIXA",
    "GENIALLOYD": "GENIALLOYD",
    "LINEAR": "LINEAR",
    "DIRECTLINE": "DIRECT LINE",
    "DIRECT LINE": "DIRECT LINE",
};

/**
 * Known marketplace/aggregator prefixes
 * These may have sub-merchant info after a separator
 */
export const MARKETPLACE_PREFIXES = [
    "AMAZON",
    "PAYPAL",
    "SUMUP",
    "STRIPE",
    "SQUARE",
    "KLARNA",
    "SATISPAY",
    "GLOVO",
    "DELIVEROO",
    "JUST EAT",
    "UBER EATS",
];

/**
 * Bridge tokens often found between marketplace and sub-merchant
 * e.g., "AMAZON *MARKETPLACE* ACME"
 */
export const BRIDGE_TOKENS = [
    "MARKETPLACE",
    "MKTP",
    "EU",
    "SRL",
    "SPA",
    "LU",
    "IE",
    "IT",
    "FR",
    "DE",
    "ES",
    "UK",
    "GB",
    "COM",
    "BV",
    "LTD",
    "GMBH",
    "SA",
    "AG",
];

/**
 * Separator patterns for sub-merchant extraction
 */
export const SUB_MERCHANT_SEPARATORS = [
    " * ",
    " *",
    "* ",
    "*",
    " # ",
    " - ",
    " / ",
    " : ",
    "@",
    "PAGAMENTO A ",
    "SELLER ",
    "MARKETPLACE ",
    "MKTP ",
    "VIA ",
    "PRESSO ",
];
