import {
    Utensils,
    Bus,
    Home,
    Gamepad2,
    HeartPulse,
    ShoppingBag,
    Plane,
    GraduationCap,
    TrendingUp,
    HelpCircle,
    Zap,
    Car,
    Shield,
    FileText,
    Users,
    Sparkles,
    Wrench,
    UtensilsCrossed,
    Sparkle,
    Dumbbell,
    Tv,
    PawPrint,
    Laptop,
    Gift,
    Armchair,
    BookOpen,
    Smartphone,
    Gem,
    Dice5,
    Briefcase,
    User,
    UserCheck,
    BadgeDollarSign,
    Building2,
    Recycle,
    CreditCard,
    Coins,
    Trophy,
    LucideIcon
} from "lucide-react"

export const ICON_REGISTRY: Record<string, LucideIcon> = {
    utensils: Utensils,
    bus: Bus,
    home: Home,
    gamepad2: Gamepad2,
    heartPulse: HeartPulse,
    shoppingBag: ShoppingBag,
    plane: Plane,
    graduationCap: GraduationCap,
    trendingUp: TrendingUp,
    zap: Zap,
    car: Car,
    shield: Shield,
    fileText: FileText,
    users: Users,
    sparkles: Sparkles,
    wrench: Wrench,
    utensilsCrossed: UtensilsCrossed,
    sparkle: Sparkle,
    dumbbell: Dumbbell,
    tv: Tv,
    pawPrint: PawPrint,
    laptop: Laptop,
    gift: Gift,
    armchair: Armchair,
    bookOpen: BookOpen,
    smartphone: Smartphone,
    gem: Gem,
    dice5: Dice5,
    briefcase: Briefcase,
    user: User,
    userCheck: UserCheck,
    badgeDollarSign: BadgeDollarSign,
    building2: Building2,
    recycle: Recycle,
    creditCard: CreditCard,
    coins: Coins,
    trophy: Trophy,
    helpCircle: HelpCircle
}

export const getIconByName = (name: string): LucideIcon => {
    return ICON_REGISTRY[name] || HelpCircle
}
