import {
    Utensils,
    Bus,
    Home,
    Gamepad2,
    HeartPulse,
    ShoppingBag,
    Plane,
    GraduationCap,
    TrendingUp,
    HelpCircle,
    Zap,
    Car,
    Shield,
    FileText,
    Users,
    Sparkles,
    Wrench,
    UtensilsCrossed,
    Sparkle,
    Dumbbell,
    Tv,
    PawPrint,
    Laptop,
    Gift,
    Armchair,
    BookOpen,
    Smartphone,
    Gem,
    Dice5,
    Briefcase,
    User,
    UserCheck,
    BadgeDollarSign,
    Building2,
    Recycle,
    CreditCard,
    Coins,
    Trophy,
    Music,
    Film,
    Camera,
    Mic,
    Headphones,
    Ticket,
    Coffee,
    Beer,
    Wine,
    Pizza,
    Sandwich,
    Cake,
    MapPin,
    Globe,
    Sun,
    Cloud,
    Umbrella,
    Tent,
    Palmtree,
    Mountain,
    Bike,
    TrainFront,
    Truck,
    Ship,
    Anchor,
    Baby,
    Dog,
    Cat,
    Flower,
    Shirt,
    Glasses,
    Watch,
    Key,
    Lock,
    Bell,
    Mail,
    MessageCircle,
    Phone,
    Calendar,
    Clock,
    Tag,
    Bookmark,
    LucideIcon
} from "lucide-react"

export const ICON_REGISTRY: Record<string, LucideIcon> = {
    utensils: Utensils,
    bus: Bus,
    home: Home,
    gamepad2: Gamepad2,
    heartPulse: HeartPulse,
    shoppingBag: ShoppingBag,
    plane: Plane,
    graduationCap: GraduationCap,
    trendingUp: TrendingUp,
    zap: Zap,
    car: Car,
    shield: Shield,
    fileText: FileText,
    users: Users,
    sparkles: Sparkles,
    wrench: Wrench,
    utensilsCrossed: UtensilsCrossed,
    sparkle: Sparkle,
    dumbbell: Dumbbell,
    tv: Tv,
    pawPrint: PawPrint,
    laptop: Laptop,
    gift: Gift,
    armchair: Armchair,
    bookOpen: BookOpen,
    smartphone: Smartphone,
    gem: Gem,
    dice5: Dice5,
    briefcase: Briefcase,
    user: User,
    userCheck: UserCheck,
    badgeDollarSign: BadgeDollarSign,
    building2: Building2,
    recycle: Recycle,
    creditCard: CreditCard,
    coins: Coins,
    trophy: Trophy,
    helpCircle: HelpCircle,
    // Entertainment
    music: Music,
    film: Film,
    camera: Camera,
    mic: Mic,
    headphones: Headphones,
    ticket: Ticket,
    // Food & Drink
    coffee: Coffee,
    beer: Beer,
    wine: Wine,
    pizza: Pizza,
    sandwich: Sandwich,
    cake: Cake,
    // Travel
    mapPin: MapPin,
    globe: Globe,
    sun: Sun,
    cloud: Cloud,
    umbrella: Umbrella,
    tent: Tent,
    palmtree: Palmtree,
    mountain: Mountain,
    // Transport
    bike: Bike,
    trainFront: TrainFront,
    truck: Truck,
    ship: Ship,
    anchor: Anchor,
    // Lifestyle
    baby: Baby,
    dog: Dog,
    cat: Cat,
    flower: Flower,
    shirt: Shirt,
    glasses: Glasses,
    watch: Watch,
    // Tools / Misc
    key: Key,
    lock: Lock,
    bell: Bell,
    mail: Mail,
    messageCircle: MessageCircle,
    phone: Phone,
    calendar: Calendar,
    clock: Clock,
    tag: Tag,
    bookmark: Bookmark
}

export const getIconByName = (name: string): LucideIcon => {
    return ICON_REGISTRY[name] || HelpCircle
}
